### ISSUE TITLE
Use GH-pages so we can see what the latest in `master` is

### ISSUE THREAD

**Issue by dominikwilkowski** [russmaxdesign/web-usability-resources#1]
Is it cool with you folk if I make master the `gh-pages` branch?
That way we can see what we have so far and don't rely on a local install after we merge a PR.
Now with GitHub allowing us to select the branch we don't even have to merge it anywhere :)

**Comment by russmaxdesign** [comment]
👍  go for it!

**Comment by dominikwilkowski** [comment]
Ups sorry you have to do it. I don't have access to the settings:

![Settings](https://cloud.githubusercontent.com/assets/3477155/17778792/47c2ecc4-6533-11e6-828a-91980daa7297.gif)

**Comment by dominikwilkowski** [comment]
(set it to `master`)

**Comment by russmaxdesign** [comment]
@dominikwilkowski Sorry for the slowness, done: https://russmaxdesign.github.io/web-usability-resources/

**Comment by dominikwilkowski** [comment]
Awesome! Thanks Russ.
Sorry been super busy getting the network status tool out: https://github.com/dominikwilkowski/status

Now more time for this!

**Comment by russmaxdesign** [comment]
All good, we're all busy. The tool looks great. Would love to hear more about it
