### ISSUE TITLE
new page "Australasian Bitterns"

### ISSUE THREAD

**Issue by dominikwilkowski** [russmaxdesign/web-usability-resources#3]
content:
- [x] slide show on top
- [x] tabs for "Distribution", "Habitat" and "Threats"
- [x] accordion for "Feeding", "Breeding" and "Movement patterns"

**Comment by RogerHudson** [comment]
Hi Dom,
This all sounds good. 
Do you want me to send you the text for the different sections of the page?

**Comment by dominikwilkowski** [comment]
Just some questions for @russ-ambiata @russmaxdesign _(not sure which persona you're using here)_ on code style. No stress I don't want to make thing complicated, just getting on the same page.
1. Are we cool with jquery? OR should it be vanilla?
2. For the slider I was thinking of using [Slick](http://kenwheeler.github.io/slick/)
3. Inline script still good?
4. I noticed you converted to spaces from tabs so I'll go with that
5. No preprocessor which is fine for the sake of making it less complicated
6. Should I make a seperate CSS and JS file for the three modules? (accordion, tabs and slider)

That's that for now :)
Thanks

**Comment by RogerHudson** [comment]
Hi,
If possible I think it would be good if all the CSS and JS that relates to  bird pages is inside the same files in the oz-bird folder - that will make it a little easier to use in the workshop. However, if you want to put some specific CSS and/or JS that relates to a particular page in the code for that page I am also cool with that.
Since the workshop I am doing is not about coding, but about accessibility and testing I don't have any problems with you using jQuery or anything else for that matter so long as the actual bird pages  end up being accessible.
Thanks.
PS I like this github racket.
Did you get the Australasain Bittern content I sent earlier? I can't see it now.

**Comment by dominikwilkowski** [comment]
Hey @RogerHudson 

Yes I got your content. You posted it to the other issue.
Ok I keep all code to the oz-birds project inside that file and inline js into the new page I create. I keep the CSS in the same file in `stylesheets/birds.css`.
Any other things can be discussed in the PR later.
Cheers :)

**Comment by russmaxdesign** [comment]
_Are we cool with jquery? OR should it be vanilla?_

Whatever you prefer. And/or what you think could be easier for low-end users

_For the slider I was thinking of using Slick_

Cool

_Inline script still good?_

Inline or external - up to you

_I noticed you converted to spaces from tabs so I'll go with that_

Yes, I have always been a tabs person but my latest team have forced me down that rouite so it has become a new habit  :)

_No preprocessor which is fine for the sake of making it less complicated_

Agree. I am a huge fan of SASS/LESS but not ideal for workshops and users would then need to run a preprocess tool or grunt/gulf file.

**Comment by dominikwilkowski** [comment]
> Yes, I have always been a tabs person but my latest team have forced me down that rouite so it has become a new habit :)

I totally agree to work with whatever the style is in a given project but don't get used to it. Tabs are literally the semantic character for indents. ayayaya... the pain :)

I have most of it done but need to fix some stuff here and there plus add the help bubbles to the tabs and accordions. Monday I'm at [Generate](http://www.generateconf.com/) so will finish likely on Tuesday evening. I am sure you guys will have changes for me after so it's good to have some time.

Cheers :)
