### ISSUE TITLE
adjust homepage

### ISSUE THREAD

**Issue by dominikwilkowski** [russmaxdesign/web-usability-resources#4]
- [x] move registration form into modal
- [x] add alert to top of page

**Comment by RogerHudson** [comment]
Hi Dom,
With registration modal, the actual registration page should stay where it is. And, only the section of the page that relates to registering (i.e. the main content) is displayed in a modal that is triggered by clicking the link on the Home page. This means that people who are unable to access the modal from the home page can still get to a page where they can register.
Thanks.

**Comment by RogerHudson** [comment]
Hi Dom,

I am going to try to attach a word file with the content for the Aust Bitterns page - you will notice I have changed the accordion 'Movement patterns" to "Hiding".
Thanks
[Australasian Bittern content.docx](https://github.com/russmaxdesign/web-usability-resources/files/453074/Australasian.Bittern.content.docx)
